infra/mysql/Dockerfile
infra/mysql/start.sh
infra/nginx/conf.d/app-server.conf
infra/nginx/conf.d/nginx.conf

#17
- mysql dockerfile
- nginx conf 파일
> ### etc

Deploy: 인프라 관련 dockerfile 및 설정파일 작성

---

.github/workflows/prod-app-api-cd.yml
cakk-api/src/main/java/com/cakk/api/dto/request/shop/CreateShopRequest.java
cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/common/base/ProviderTest.java
cakk-common/src/main/java/com/cakk/common/enums/DayOfWeek.java
cakk-common/src/main/java/com/cakk/common/enums/Days.java
cakk-domain/src/main/java/com/cakk/domain/converter/DayOfWeekConverter.java
cakk-domain/src/main/java/com/cakk/domain/entity/cake/CakeShopOperation.java
cakk-domain/src/main/java/com/cakk/domain/entity/user/BusinessInformation.java
cakk-domain/src/main/java/com/cakk/domain/repository/jpa/CakeShopOperationJpaRepository.java
cakk-domain/src/main/java/com/cakk/domain/repository/writer/CakeShopWriter.java

#21 
- 케이크샵 등록은 현재 Admin에 의해 API로 등록되기 때문에 Validation은 넣지 않았음
- 테스트 코드 오류 있는거는 다음 이슈로 해결하겠습니다
```java
```
> ### etc

Fix: 사업자 등록 관련 비즈니스 로직 수정

---

cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShop.java

#26 
- 엔티티 생성 시, 에러 수정
```java
```
> ### etc

Fix: Entity 생성 시 Default Value 지정

---

cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-common/src/main/java/com/cakk/common/enums/Role.java
cakk-domain/src/main/java/com/cakk/domain/entity/user/BusinessInformation.java
cakk-domain/src/main/java/com/cakk/domain/entity/user/User.java
cakk-domain/src/main/java/com/cakk/domain/repository/jpa/BusinessInformationJpaRepository.java
cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopReader.java

#28 
- 쿼리 수정
- 권한 변경 로직 추가
```java
```
> ### etc

Fix: 조회 쿼리 수정 및 비즈니스 로직 중 권한 변경 빠진 부분 추가

---

cakk-domain/src/test/java/com/cakk/domain/base/DomainTest.java
cakk-domain/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java

#30 
- 테스트 코드 개선
```java
```
> ### etc

Test: CakeShop도메인 테스트 코드 리팩토링

---

cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopDetailResponse.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopDetailParam.java
cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopLinkParam.java
cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeShopQueryRepository.java
cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopReader.java

#24
- 케이크 샵 상세조회 비즈니스 로직 구현
```java
. . .
public CakeShopDetailParam searchDetailById(Long cakeShopId) {
List<CakeShopDetailParam> results = queryFactory
.selectFrom(cakeShop)
.innerJoin(cakeShopOperation)
.on(cakeShop.eq(cakeShopOperation.cakeShop))
.innerJoin(cakeShopLink)
.on(cakeShop.eq(cakeShopLink.cakeShop))
.where(eqCakeShopId(cakeShopId))
.transform(groupBy(cakeShop.id)
.list(Projections.constructor(CakeShopDetailParam.class,
cakeShop.id,
cakeShop.shopName,
cakeShop.thumbnailUrl,
cakeShop.shopBio,
cakeShop.shopDescription,
list(Projections.constructor(Days.class,
cakeShopOperation.operationDay)
),
list(Projections.constructor(CakeShopLinkParam.class,
cakeShopLink.linkKind,
cakeShopLink.linkPath)
)
)));
return results.isEmpty() ? …
```

Feature: 케이크 샵 상세조회 비즈니스 로직 구현

---

cakk-api/src/main/resources/application.yml

#55 
- DDL 수정
```java
```
> ### etc

Hotfix: DDL 수정

---

cakk-api/src/main/resources/application.yml

#57 
- ddl 수정
```java
```
> ### etc

Hotfix: prod 환경에서 DDL update로 수정

---

cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeImageSearchRequest.java
cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/cake/CakeSearchParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeTagQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeReader.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeTagReader.java

#59
- QueryDSL 기반으로 위치기반 검색조회를 수행할 수 있게되어 다른 코드들도 리팩토링 할 예정입니다
```java
```
> ### etc

Feature: 케이크 검색 기능 추가

---

cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/resources/sql/insert-cake.sql
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java

#82 
- 검색을 위한 테이블 Join에서 발생하는 중복을 Distinct 키워드로 제거하고 insert script에 맞게 올바른 데이터를 가져오도록 수정합니다
```java
```
> ### etc

Fix: 케이크 검색 조회 오류 수정

---

cakk-api/spy.log
cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeSearchByViewsRequest.java
cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/service/cake/CakeServiceTest.java
cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeReader.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/CakeViewRedisRepository.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/RedisZSetTemplate.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/impl/RedisLongZSetTemplate.java

#80
인기 케이크 조회를 구현했습니다. 로직은 메신저를 통해 논의했던 내용과 동일합니다. 나중에 로직 개선해보시죠~
```java
public CakeImageListResponse searchCakeImagesByCursorAndViews(final CakeSearchByViewsRequest dto) {
final List<Long> cakeIds = cakeViewRedisRepository.findTopCakeIdsByOffsetAndCount(dto.cursor(), dto.pageSize());
if (isNull(cakeIds) || cakeIds.isEmpty()) {
return CakeMapper.supplyCakeImageListResponse(List.of(), cakeIds);
}
final List<CakeImageResponseParam> cakeImages = cakeReader.searchCakeImagesByCakeIds(cakeIds);
return CakeMapper.supplyCakeImageListResponse(cakeImages, cakeIds);
}
```
> ### etc

Feature: 인기 케이크 조회 구현

---

cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/dto/request/shop/UpdateShopRequest.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/CakeShopUpdateParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java

#87 
- 케이크 샵 기본 정보 수정 테스트 추가
- 도메인 로직 추가
- querydsl 을 활용한 fetch join
```java
public void updateDefaultInformation(CakeShopUpdateParam param) {
User owner = param.user();
if (isNotOwner(owner)) { // 케이크샵을 수정하는 사람이 주인이 아니라면
throw new CakkException(ReturnCode.NOT_CAKE_SHOP_OWNER); // 예외 발생
}
shopName = param.shopName();
shopBio = param.shopBio();
shopDescription = param.shopDescription();
}
```
> ### etc
도메인 로직에서 CakeShop이 가지는 책임을 자신의 필드에 대한 Length까지 검증을 해야할까? 에 대해 의견 주시면 감사합니다

Feature: 케이크 샵 기본 정보 수정 기능 추가

---

cakk-api/build.gradle
cakk-api/src/main/java/com/cakk/api/annotation/DistributedLock.java
cakk-api/src/main/java/com/cakk/api/aspect/AopForTransaction.java
cakk-api/src/main/java/com/cakk/api/aspect/DistributedLockAspect.java
cakk-api/src/main/java/com/cakk/api/config/AspectConfig.java
cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
cakk-api/src/test/java/com/cakk/api/service/like/HeartConcurrencyTest.java
cakk-api/src/test/java/com/cakk/api/service/like/HeartServiceTest.java
cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
cakk-domain/redis/build.gradle
cakk-domain/redis/src/main/java/com/cakk/domain/redis/config/RedisConfig.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/dto/param/ExecuteWithLockParam.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/LockRedisRepository.java

#91
락 관련하여 리팩토링 진행했습니다. ~블로그를 작성중인데, 끝나면 첨부하겠습니다.~
관련 내용 첨부합니다. [작성한 블로그](https://velog.io/@komment/concurrency-shadow-boxing)
```java
@Around("@annotation(com.cakk.api.annotation.DistributedLock)")
public Object lock(final ProceedingJoinPoint joinPoint) throws Throwable {
final MethodSignature signature = (MethodSignature) joinPoint.getSignature();
final Method method = signature.getMethod();
final DistributedLock distributedLock = method.getAnnotation(DistributedLock.class);
final RedisKey key = RedisKey.getLockByMethodName(method.getName());
final ExecuteWithLockParam param = ExecuteWithLockParam.builder()
.key(key)
.waitTime(distributedLock.waitTime())
.leaseTime(distributedLock.leaseTime())
.timeUnit(distributedLock.timeUnit()) …
```

Refactor: 분산 락 관련 리팩토링

---

cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/service/like/LikeService.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/service/like/HeartServiceTest.java
cakk-api/src/test/java/com/cakk/api/service/like/LikeConcurrencyTest.java
cakk-api/src/test/java/com/cakk/api/service/like/LikeServiceTest.java
cakk-api/src/test/resources/sql/delete-all.sql
cakk-api/src/test/resources/sql/insert-like-for-concurrency-test.sql
cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShopLike.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeShopLikeJpaRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopLikeReader.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopLikeWriter.java

#89 
케이크 샵 좋아요 기능을 구현했습니다. 트랜잭션 범위를 줄이기 위해 유효성 검사를 따로 분리했습니다. 
```java
```
> ### etc

Feature: 케이크샵 좋아요 구현

---

cakk-external/src/main/java/com/cakk/external/service/S3Service.java

#95 
- 확장자를 추가했습니다
```java
```
> ### etc

Hotfix: 이미지 업로드를 위한 presigned url 생성 방법 수정

---

cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/dto/request/operation/ShopOperationParam.java
cakk-api/src/main/java/com/cakk/api/dto/request/operation/UpdateShopOperationRequest.java
cakk-api/src/main/java/com/cakk/api/dto/request/shop/UpdateShopAddressRequest.java
cakk-api/src/main/java/com/cakk/api/mapper/ShopOperationMapper.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/operation/UpdateShopOperationParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/UpdateShopAddressParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShopOperation.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeShopJpaRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java

#87 
- 기존과 비슷한 로직입니다.
```java
public void updateShopAddress(UpdateShopAddressParam param) { // 주소 변경
shopAddress = param.shopAddress();
location = param.location();
}
public void updateShopOperationDays(List<CakeShopOperation> cakeShopOperations) { // 영업일 변경
this.cakeShopOperations.clear();
cakeShopOperations.forEach(cakeShopOperation -> {
cakeShopOperation.updateCakeShop(this);
this.cakeShopOperations.add(cakeShopOperation);
});
}
```
> ### etc

Feature: 케이크 샵 영업일 및 주소 업데이트 기능 추가

---

cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeUpdateRequest.java
cakk-api/src/main/java/com/cakk/api/mapper/CakeDesignCategoryMapper.java
cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/resources/sql/insert-cake.sql
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/cake/CakeUpdateParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/CakeCategory.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/CakeTag.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Tag.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/CakeTagMapper.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/TagMapper.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/TagJpaRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeReader.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/TagReader.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeWriter.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/TagWriter.java

#88 
- 케이크 수정, 삭제 기능 추가입니다.
- 큰 로직은 없이 도메인 로직으로 감쌌습니다.
```java
@Transactional
public void updateCake(CakeUpdateParam param) { // 케이크 수정
final Cake cake = cakeReader.findWithCakeTagsAndCakeCategories(param.cakeId(), param.owner());
List<Tag> tags = param.tagNames()
.stream()
.map(tagName -> tagReader.findByTagName(tagName).orElseGet(() -> tagWriter.saveTag(tagName)))
.toList();
cake.updateCakeImageUrl(param.cakeImageUrl());
cake.updateCakeCategories(param.cakeCategories());
cake.updateCakeTags(tags);
}
@Transactional
public void deleteCake(User owner, Long cakeId) { // 케이크 삭제
final Cake cake = cakeReader.findWithCakeTagsAndCakeCategories(cakeId, owner);
cake.removeCakeCategories();
cake.removeCakeTags();
cakeWriter.deleteCake(cake);
} …
```

Feature: 케이크 수정, 삭제 기능 추가

---

cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/dto/response/like/HeartResponse.java
cakk-api/src/main/java/com/cakk/api/mapper/HeartMapper.java
cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeHeartJpaRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeShopHeartJpaRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeHeartReader.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopHeartReader.java

#105
별다른 로직 없이 jpa를 활용한 exist 쿼리를 사용했습니다.
```java
@Transactional(readOnly = true)
public HeartResponse isHeartCake(final User user, final Long cakeId) {
final Cake cake = cakeReader.findById(cakeId);
final boolean isHeart = cakeHeartReader.existsByUserAndCake(user, cake);
return HeartMapper.supplyHeartResponseBy(isHeart);
}
@Transactional(readOnly = true)
public HeartResponse isHeartCakeShop(final User user, final Long cakeShopId) {
final CakeShop cakeShop = cakeShopReader.findById(cakeShopId);
final boolean isHeart = cakeShopHeartReader.existsByUserAndCakeShop(user, cakeShop);
return HeartMapper.supplyHeartResponseBy(isHeart);
}
```
> ### etc

Feature: 케이크 및 케이크샵 하트 여부 조회 구현

---

cakk-api/src/main/resources/application.yml

#111 
- ddl 변경
```java
```
> ### etc

Hotfix: 테이블 컬럼 변경으로 인한 ddl 변경

---

cakk-api/src/main/resources/application.yml
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopOperationQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeReader.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopOperationReader.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java

#111 
- 원상태로 복구 및 사용하지 않는 메서드 제거
```java
```
> ### etc

Hotfix: 테이블 컬럼 변경으로 인한 ddl 복구

---

cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopOwnerResponse.java
cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/BusinessInformationJpaRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/BusinessInformationReader.java

#110 
- 케이크 샵 사업자 연동 여부 조회
```java
```
> ### etc

Feature: 케이크샵 사업자 연동 여부 조회

---

cakk-external/src/main/java/com/cakk/external/service/S3Service.java

#116 
- 사진 확장자 변경
```java
```
> ### etc

Hotfix: 사진 확장자 변경

---

cakk-api/src/main/java/com/cakk/api/dto/request/shop/CreateShopRequest.java

#118 
- 기획자 요청으로 인한 검증 애노테이션 제거
```java
```
> ### etc

Hotfix: 백오피스 API에서 사업자인증번호 Validation 제거

---

cakk-api/src/main/resources/application.yml
cakk-batch/build.gradle
cakk-batch/src/main/java/com/cakk/batch/BatchApplication.java
cakk-batch/src/main/java/com/cakk/batch/config/ComponentScanConfig.java
cakk-batch/src/main/java/com/cakk/batch/controller/WeeklyJobController.java
cakk-batch/src/main/java/com/cakk/batch/handler/LambdaHandler.java
cakk-domain/mysql/build.gradle

#120
Batch 서버에 Aws Lambda 관련 설정을 추가하였고, zip 파일로 말아서 배포했습니다. workflow는 테스트 과정에서 master에 이미 넣어버렸습니다. 🥲
```java
```
> ### etc

Feature: Batch 서버 Lambda 핸들러 구현

---

cakk-api/src/main/java/com/cakk/api/controller/advice/GlobalControllerAdvice.java
cakk-api/src/main/java/com/cakk/api/dto/request/link/ShopLinkParam.java
cakk-api/src/main/java/com/cakk/api/dto/request/shop/CreateShopRequest.java
cakk-api/src/main/java/com/cakk/api/mapper/LinkMapper.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/main/java/com/cakk/api/validator/OperationValidator.java
cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopWriter.java

#125 
- 케이크샵 링크 추가
- 클라이언트와 API 테스트 과정에서 log 문제가 있어서 일부 수정
```java
```
> ### etc

Refactor: 케이크샵 등록 시, 외부 링크 추가

---

cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/CakeCategory.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/CakeHeart.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/CakeTag.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Tag.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShopHeart.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShopLike.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShopLink.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShopOperation.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/BusinessInformation.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/User.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/UserWithdrawal.java

#128
- do
- do
```java
```
> ### etc

Deploy: 배포 준비

---

cakk-external/src/main/java/com/cakk/external/service/MailService.java

#0
- do
- do
```java
```
> ### etc

Refactor: mail 전송 관련 에러 로그 추가

---

cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopByMineResponse.java
cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/BusinessInformationJpaRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/BusinessInformationReader.java

#134 
- 나의 케이크샵 조회 API 추가
- 테스트 추가
```java
```
> ### etc

Feature: 나의 케이크샵 아이디 조회

---

cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-api/src/test/resources/sql/insert-test-user.sql
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java

#136 
- USER권한 Admin시, API 사용 권한 조건부 동적 쿼리로 수정
- USER권한 Admin시, API 사용 테스트 추가
```java
```
> ### etc

Hotfix: USER 권한에 따른 API 사용 권한 부여

---

cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java

#136 
- 쿼리 수정
```java
```
> ### etc

Hotfix: 케이크샵 조회 시, 권한에 따른 조건 수정

---

cakk-api/src/main/java/com/cakk/api/config/SecurityConfig.java
cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeUpdateRequest.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeShopJpaRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java

#136
- 케이크 생성 시 쿼리 수정
```java
```
> ### etc

Hotfix:  케이크 생성 시 사용 쿼리 수정

---

cakk-api/src/main/java/com/cakk/api/listener/views/ViewsIncreaseEventListener.java
cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/service/cake/CakeServiceTest.java
cakk-batch/src/main/java/com/cakk/batch/tasklet/ClearViewsCakeIdListTasklet.java
cakk-batch/src/main/java/com/cakk/batch/tasklet/FindViewsCakeIdListTaskLet.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/CakeViewsRedisRepository.java

#133
네이밍 수정만 있습니다.
```java
```
> ### etc

Refactor: 조회수 레포지토리 네이밍 수정

---

cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java

#136 
- 쿼리 수정
```java
```
> ### etc

Hotfix: 케이크 상세 조회 쿼리 오류 수정

---

cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/resources/sql/insert-cake.sql

#136 
- 테스트 추가
- response 수정
```java
```
> ### etc

Hotfix: 케이크 카테고리 및 태그 존재 유무에 따른 테스트 및 response 수정

---

cakk-api/src/main/java/com/cakk/api/listener/views/ViewsIncreaseEventListener.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/main/java/com/cakk/api/service/slack/SlackService.java
cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/event/EventMapper.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/event/views/CakeShopIncreaseViewsEvent.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/CakeShopViewsRedisRepository.java

#133
케이크 조회수 로직과 동일합니다. 이후 인기 케이크샵 조회 로직을 구현할 예정입니다.
```java
```
> ### etc

Feature: 케이크 샵 조회수 상승 로직 구현

---

cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java

#144 
- 케이크 검색 시, Tag Inner Join -> left Join으로 변경
- 케이크 상세 조회 시, 영업일 관련 Inner Join -> left Join으로 변경
- 케이크 및 케이크샵 검색 시, 위치 기반 10km로 변경
```java
```
> ### etc

Hotfix: 케이크 검색, 상세 조회 쿼리 수정

---

cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/CakeShops.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/CakeShopParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java

#147 
- 쿼리 수정
```java
```
> ### etc

Hotfix: 위치 기반 검색 쿼리 오류 및 케이크 샵 정보 조회 쿼리 수정

---

cakk-api/src/main/java/com/cakk/api/annotation/AccessToken.java
cakk-api/src/main/java/com/cakk/api/config/SecurityConfig.java
cakk-api/src/main/java/com/cakk/api/config/WebMvcConfig.java
cakk-api/src/main/java/com/cakk/api/controller/user/SignController.java
cakk-api/src/main/java/com/cakk/api/provider/jwt/JwtProvider.java
cakk-api/src/main/java/com/cakk/api/resolver/AccessTokenResolver.java
cakk-api/src/main/java/com/cakk/api/service/user/SignService.java
cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
cakk-api/src/test/java/com/cakk/api/integration/user/SignIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/provider/JwtProviderTest.java
cakk-api/src/test/java/com/cakk/api/service/user/SignServiceTest.java
cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/TokenRedisRepository.java

#62
로그아웃 기능을 구현하였습니다. 헤더로 받은 두 토큰을 블랙리스트에 저장하는 간단한 로직이고, 토큰 확인 시 블랙리스트인지 확인하는 로직도 추가하였습니다.
```java
public void signOut(final String accessToken, final String refreshToken) {
final long accessTokenExpiredSecond = jwtProvider.getTokenExpiredSecond(accessToken) - System.currentTimeMillis();
final long refreshTokenExpiredSecond = jwtProvider.getTokenExpiredSecond(refreshToken) - System.currentTimeMillis();
tokenRedisRepository.registerBlackList(accessToken, accessTokenExpiredSecond);
tokenRedisRepository.registerBlackList(refreshToken, refreshTokenExpiredSecond);
}
```
> ### etc

Feature: 로그아웃 기능 구현

---

cakk-api/src/main/java/com/cakk/api/annotation/DistributedLock.java
cakk-api/src/main/java/com/cakk/api/aspect/DistributedLockAspect.java
cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
cakk-api/src/main/java/com/cakk/api/service/like/LikeService.java
cakk-api/src/main/java/com/cakk/api/utils/CustomSpringExpressionLanguageParser.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/dto/param/ExecuteWithLockParam.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/LockRedisRepository.java

#159
- SpEL Parser 구현
- Lock Key 생성 방식 관련 리팩토링
```java
private String generateKey(final Method method, final String key, final String[] parameterNames, final Object[] args) {
String generatedKey = RedisKey.getLockByMethodName(method.getName()).getValue();
generatedKey += CustomSpringExpressionLanguageParser.getDynamicValue(key, parameterNames, args);
return generatedKey;
}
```
> ### etc

Refactor | #159 | @lcomment | SpEL을 활용한 Lock Key 리팩토링

---

.github/workflows/ci.yml
codecov.yml

#155
code coverage를 시각화 하기 위해 codecov를 연동했습니다
```java
```
> ### etc

Chore | #155 | @lcomment | codecov 연동

---

cakk-api/src/main/java/com/cakk/api/dto/event/IncreaseSearchCountEvent.java
cakk-api/src/main/java/com/cakk/api/listener/CertificationEventListener.java
cakk-api/src/main/java/com/cakk/api/listener/EmailSendEventListener.java
cakk-api/src/main/java/com/cakk/api/listener/SearchEventListener.java
cakk-api/src/main/java/com/cakk/api/listener/ViewsIncreaseEventListener.java
cakk-api/src/main/java/com/cakk/api/mapper/EventMapper.java
cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/listener/EmailSendEventListenerTest.java
cakk-api/src/test/java/com/cakk/api/listener/SearchEventListenerTest.java

#163 
인기검색어가 조회되지 않는 이슈를 해결합니다.
```java
```
> ### etc

Hotfix | #163 | @lcomment | 인기검색어 조회 관련 이슈 해결

---

cakk-api/src/main/java/com/cakk/api/dto/request/shop/SearchShopByLocationRequest.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java

#165
* Feature | #165 | @YongsHub | 위치 기반 검색에서 거리 파라미터 추가
* Fix | #165 | @YongsHub | 위치 기반 검색 시, 기존 요구사항 5km 또는 클라이언트 요청 범위로 변경
* Fix | #165 | @YongsHub | 기본 거리 1km로 변경
* Test | #165 | @YongsHub | 테스트 코드 리팩토링
```java
```
> ### etc

Deploy: 2.0.2.1

---

cakk-domain/redis/src/main/java/com/cakk/domain/redis/config/RedisConfig.java
infra/redis/docker-compose.yaml

#170 
- 패스워드 설정
- 볼륨 위치 변경
- prod에 패스워드 추가
```java
```
> ### etc

Hotfix: Redis 패스워드 설정 및 볼륨 변경

---

cakk-api/src/main/java/com/cakk/api/config/CertificationTemplateConfig.java
cakk-api/src/main/java/com/cakk/api/listener/CertificationEventListener.java
cakk-api/src/main/java/com/cakk/api/mapper/EventMapper.java
cakk-api/src/main/java/com/cakk/api/service/slack/SlackService.java
cakk-api/src/main/java/com/cakk/api/template/CertificationTemplate.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-api/src/test/resources/sql/insert-cake-shop.sql
cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/config/RedisConfig.java
cakk-external/build.gradle
cakk-external/src/main/java/com/cakk/external/executor/CertificationApiExecutor.java
cakk-external/src/main/java/com/cakk/external/executor/CertificationSlackApiExecutor.java
cakk-external/src/main/java/com/cakk/external/extractor/CertificationMessageExtractor.java
cakk-external/src/main/java/com/cakk/external/extractor/CertificationSlackMessageExtractor.java
cakk-external/src/main/java/com/cakk/external/vo/CertificationMessage.java
infra/redis/docker-compose.yaml

#
- 사장 인증 로직 리팩토링
- Redis 패스워드 설정
```java
```
> ### etc

Deploy: v2.0.2.2 배포

---

cakk-domain/redis/src/main/java/com/cakk/domain/redis/config/RedisConfig.java

#0
- do
- do
```java
```
> ### etc

Deploy: v2.0.2.2

---

cakk-api/src/test/java/com/cakk/api/common/container/RedisTestContainer.java

#0
- do
- do
```java
```
> ### etc

Deploy: 2.0.0.2 배포

---

cakk-api/src/main/java/com/cakk/api/controller/shop/AdminController.java
cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopOwnerCandidateResponse.java
cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopOwnerCandidatesResponse.java
cakk-api/src/main/java/com/cakk/api/mapper/BusinessInformationMapper.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/integration/admin/AdminIntegrationTest.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/BusinessInformationJpaRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/BusinessInformationReader.java

-  케이크샵 인증 상세 내용 조회 API
해당 애플리케이션 로직은 상세 조회 밖에 없어서 별 내용 없고 테스트 코드로 어떤 데이터 조회하는지 확인하시면 될 것 같습니다
기획자 통해서 제공 요청 받은 데이터 입니다.
다음 PR에서 이전에 언급한 불필요한 로직 개선 진행하겠습니다
```java
```
> ### etc

Feature: 사장님 인증 요청 상세 내용 조회 API 개발

---

build.gradle.kts
cakk-admin/build.gradle.kts
cakk-admin/src/main/kotlin/com/cakk/admin/AdminApplication.kt
cakk-admin/src/main/kotlin/com/cakk/admin/config/ComponentScanConfig.kt
cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/OwnerCandidateParam.kt
cakk-admin/src/main/kotlin/com/cakk/admin/dto/response/CakeShopOwnerCandidateResponse.kt
cakk-admin/src/main/kotlin/com/cakk/admin/dto/response/CakeShopOwnerCandidatesResponse.kt
cakk-admin/src/main/kotlin/com/cakk/admin/mapper/BusinessInformationMapper.kt
cakk-admin/src/main/kotlin/com/cakk/admin/service/ShopService.kt
gradle.properties
settings.gradle.kts

CAKK-35
일단 간단하게 설정해두었습니다. 더 이관하면서 kotlin 관련 가이드 라인 잡아보겠습니다.
```java
```
> ### etc

Chore: kotlin 설정 및 admin 모듈 이관 작업

---

.github/workflows/ci.yml
cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
cakk-api/src/main/java/com/cakk/api/service/like/LikeService.java
cakk-api/src/test/java/com/cakk/api/service/like/HeartServiceTest.java
cakk-api/src/test/java/com/cakk/api/service/like/LikeServiceTest.java
cakk-api/src/test/resources/sql/insert-cake-shop.sql
cakk-domain/mysql/build.gradle
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/annotation/DomainFacade.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/User.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/facade/user/UserHeartFacade.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/facade/user/UserLikeFacade.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/CakeShopHeartMapper.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/CakeShopLikeMapper.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopHeartWriter.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopLikeWriter.java
cakk-domain/mysql/src/test/java/com/cakk/domain/base/DomainTest.java
cakk-domain/mysql/src/test/java/com/cakk/domain/facade/user/UserHeartFacadeTest.java
cakk-domain/mysql/src/test/java/com/cakk/domain/facade/user/UserLikeFacadeTest.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/CakeShopViewsRedisRepository.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/CakeViewsRedisRepository.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/EmailVerificationRedisRepository.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/KeywordRedisRepository.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/TokenRedisRepository.java

CAKK-55
저번 PR과 비슷한 내용으로 리팩토링 했습니다. Facade 패턴을 적용했고, 다른 도메인도 적용하면서 Writer를 추가 제거할 예정입니다.
```java
```
> ### etc

Refactor | CAKK-55 | 케이크샵 하트 및 기대돼요 기능 리팩토링

---

cakk-api/src/main/kotlin/com/cakk/api/config/JacksonConfig.kt
cakk-core/src/main/kotlin/com/cakk/core/service/user/SignService.kt

CAKK-89
ObjectMapper에 코틀린 설정
```java
```
> ### etc

Hotfix | CAKK-89 | objectmapper 설정 수정

---

cakk-api/src/test/java/com/cakk/api/controller/SignControllerTest.kt
cakk-core/src/main/kotlin/com/cakk/core/facade/cake/CakeReadFacade.kt
cakk-core/src/main/kotlin/com/cakk/core/facade/cake/CakeShopReadFacade.kt
cakk-core/src/main/kotlin/com/cakk/core/service/cake/CakeService.kt
cakk-core/src/main/kotlin/com/cakk/core/service/shop/ShopService.kt
cakk-core/src/test/kotlin/com/cakk/core/service/cake/CakeServiceTest.kt
cakk-core/src/test/kotlin/com/cakk/core/service/shop/ShopServiceTest.kt

CAKK-91
기존에 Service에서 Redis에서 순위를 불러오는 로직을 Domain Facade로 옮겼습니다. 하나의 Layer(Domain Facade)가 추가 됐기에 해당 Layer가 무조건 존재하도록 나머지 코드들도 차후에 리팩토링 예정입니다. (KeywordService, Email~~~Service)
> ### etc

Refactor | CAKK-91 | 의존성 관련 리팩토링

---

cakk-api/src/main/kotlin/com/cakk/api/controller/cake/CakeController.kt
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.kt
cakk-core/src/main/kotlin/com/cakk/core/dto/response/cake/CakeImageListResponse.kt
cakk-core/src/main/kotlin/com/cakk/core/dto/response/cake/CakeImageWithShopInfoListResponse.kt
cakk-core/src/main/kotlin/com/cakk/core/facade/cake/CakeReadFacade.kt
cakk-core/src/main/kotlin/com/cakk/core/mapper/CakeMapper.kt
cakk-core/src/main/kotlin/com/cakk/core/service/cake/CakeService.kt
cakk-core/src/test/kotlin/com/cakk/core/service/cake/CakeServiceTest.kt
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/cake/CakeImageResponseParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/cake/CakeImageWithShopInfoResponseParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java

- 케이크 샵 썸네일 이미지와 가게 이름을 추가했습니다.
- 관련 테스트 코드 일부를 리팩토링해주고 상태 테스트를 추가했습니다.
- 필요 없는 Dto 제거했습니다.
```java
```
> ### etc
테스트 코드가 꼼꼼하게 작성되어 있어서 코드 수정이 진짜 편해서 좋네요

Refactor | CAKK-94 | 케이크 이미지 조회에 대한 로직 리팩토링

---

build.gradle.kts
cakk-admin/build.gradle.kts
cakk-api/build.gradle.kts
cakk-api/src/main/kotlin/com/cakk/api/dto/request/shop/SearchShopByLocationRequest.kt
cakk-api/src/test/java/com/cakk/api/provider/AppleAuthProviderTest.kt
cakk-api/src/test/java/com/cakk/api/provider/KakaoAuthProviderTest.kt
cakk-batch/build.gradle
cakk-core/build.gradle.kts
cakk-domain/mysql/build.gradle.kts
cakk-domain/redis/build.gradle.kts
cakk-external/build.gradle.kts
gradle.properties
libs.versions.toml
settings.gradle.kts

CAKK-97
- 버전 관리 변경
- 거리 검색 관련 최대 거리 수정
> ### etc

Deploy | CAKK-97 | v2.0.6 배포
