.github/workflows/ci.yml
cakk-api/src/main/java/com/cakk/api/config/GoogleConfig.java
cakk-api/src/main/java/com/cakk/api/config/JwtConfig.java
cakk-api/src/main/java/com/cakk/api/config/SlackWebhookConfig.java
cakk-api/src/main/java/com/cakk/api/controller/advice/GlobalControllerAdvice.java
cakk-api/src/main/java/com/cakk/api/provider/jwt/JwtProvider.java
cakk-api/src/main/java/com/cakk/api/service/slack/SlackService.java
cakk-api/src/test/java/com/cakk/api/common/base/ProviderTest.java
cakk-client/src/main/java/com/cakk/client/web/AppleAuthClient.java
cakk-client/src/main/java/com/cakk/client/web/KakaoAuthClient.java
cakk-client/src/main/resources/client-local.yml
cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
cakk-common/src/main/java/com/cakk/common/exception/CakkException.java
cakk-common/src/main/java/com/cakk/common/response/ApiResponse.java

#4
- Slack Webhook을 설정하고 관련 기능을 구현했습니다.
- ControllerAdvice를 활용하여 에러 핸들러를 구현했습니다.
```java
. . . 
@ExceptionHandler(CakkException.class)
public ResponseEntity<ApiResponse<Void>> handleCakkException(CakkException exception, HttpServletRequest request) {
if (exception.getReturnCode().equals(ReturnCode.EXTERNAL_SERVER_ERROR)) {
slackService.sendSlackForError(exception, request);
}
return getResponseEntity(BAD_REQUEST, ApiResponse.fail(exception.getReturnCode()));
}
. . .
```
모든 실패 응답은 400, 서버 에러는 500을 던졌습니다. Slack 관련 기능은 사업자 인증 관련해서 확장하여 사용해도 될거 같습니다.
> ### etc

Feature: Slack 웹훅 관련 기능 및 에러 핸들러 구현

---

cakk-api/src/main/java/com/cakk/api/config/AsyncConfig.java
cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/event/shop/listener/CertificationEventListener.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/main/java/com/cakk/api/service/slack/SlackService.java
cakk-common/src/main/java/com/cakk/common/response/ApiResponse.java
cakk-domain/build.gradle
cakk-domain/src/main/java/com/cakk/domain/entity/user/BusinessInformation.java
cakk-domain/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java

#14 
- FixtureMonkey를 활용한 비즈니스 로직 테스트 코드
- 테스트 코드를 작성하면서 Entity에서 EventPublisher를 계속 받아와서 이벤트를 publish까지 하는 로직은 클래스의 응집도가 떨어진다고 판단해서 로직을 변경했습니다. 따라서, 조건에 따라 EventMessage를 만들어주는 책임만을 부여했습니다
- 외부 서비스(슬랙에 메시지 전송)를 이용하는 것이 동기적으로 이루어진다면,  불필요한 병목현상이 발생하기 때문에 비동기 방식으로 변경했습니다
비즈니스 로직 코드 변경 
케이크 샵이 존재하면 케이크샵 정보와 함께 슬랙에 보낼 메시지를 Return 해주는 책임 / 없다면 유저 관련 정보만 Return 해주는 책임
```java
if (isExistMyCakeShop()) {
return EventMapper.supplyCertificationInfoWithCakeShopInfo(param, cakeShop);
}
return EventMapper.supplyCertificationInfo(param);
```
> ### etc

Feature: 사장 인증 외부 서비스 연동 및 비즈니스 로직 변경

---

.gitmodules
cakk-api/src/main/resources/application-local.yml
cakk-api/src/main/resources/application.yml

Chore: 환경변수 관리를 위한 서브모듈 구성

---

cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeSearchByCategoryRequest.java
cakk-api/src/main/java/com/cakk/api/dto/response/cake/CakeImageListResponse.java
cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
cakk-api/src/test/java/com/cakk/api/service/cake/CakeServiceTest.java
cakk-common/src/main/java/com/cakk/common/enums/CakeDesignCategory.java
cakk-domain/src/main/java/com/cakk/domain/dto/param/cake/CakeImageResponseParam.java
cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShop.java
cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeQueryRepository.java
cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeReader.java
infra/nginx/Dockerfile

#22
- 카테고리별 케이크 사진 조회 구현 (no-offset)
```java
. . .
public List<CakeImageResponseParam> findCakeImagesByCursorAndCategory(Long cakeId, CakeDesignCategory category, int pageSize) {
return queryFactory
.select(Projections.constructor(CakeImageResponseParam.class,
cakeShop.id,
cake.id,
cake.cakeImageUrl))
.from(cake)
.innerJoin(cake.cakeShop, cakeShop)
.innerJoin(cakeCategory.cake, cake)
.where(
ltCakeId(cakeId),
eqCategory(category))
.limit(pageSize)
.orderBy(cakeIdDesc())
.fetch();
}
. . .
```
> ### etc

Feature: 카테고리별 케이크 사진 조회 비즈니스 구현

---

cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
cakk-api/src/test/java/com/cakk/api/ArchitectureTest.java
cakk-api/src/test/java/com/cakk/api/common/annotation/MockCustomUser.java
cakk-api/src/test/java/com/cakk/api/common/annotation/TestWithDisplayName.java
cakk-api/src/test/java/com/cakk/api/common/config/WithMockCustomUserSecurityContextFactory.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/provider/JwtProviderTest.java
cakk-api/src/test/java/com/cakk/api/service/cake/CakeServiceTest.java
cakk-api/src/test/java/com/cakk/api/service/user/UserServiceTest.java
cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeQueryRepository.java
cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeReader.java

#34
기존, 메서드명으로 테스트 케이스 네이밍을 했는데, @DisplayName으로 명시하기로 결정돼 코드를 간소화 하기 위해 @TestWithDisplayName 어노테이션을 구현하였습니다.
```java
@TestWithDisplayName("카테고리에 해당하는 케이크 목록을 조회한다")
void findCakeImagesByCursorAndCategory1() {
. . .
```
> ### etc

Refactor: TestWithDisplayName 어노테이션 구현 및 적용

---

cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
cakk-api/src/test/resources/sql/insert-cake.sql
cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopSimpleResponse.java
cakk-domain/src/main/java/com/cakk/domain/entity/cake/Cake.java
cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeShopQueryRepository.java
cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopReader.java

#23
- 케이크 샵 하단 탭 조회 비즈니스 구현
```java
. . .
return queryFactory.select(Projections.constructor(CakeShopSimpleResponse.class,
cakeShop.id,
cakeShop.thumbnailUrl,
cakeShop.shopName,
cakeShop.shopBio
))
.from(cakeShop)
.where(eqCakeShopId(cakeShopId))
.fetchOne();
. . .
```
> ### etc

Feature: 케이크 샵 하단 탭 조회 비즈니스 구현

---

.github/workflows/ci.yml
.github/workflows/prod-app-api-cd.yml
cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-api/src/test/resources/sql/insert-cake-shop.sql

#23
케이크 샵 간단조회 API를 구현하고, 통합 테스트를 작성했습니다. id 조회다보니 TC는 2건입니다.
```java
. . .
@GetMapping("/{cakeShopId}/simple")
public ApiResponse<CakeShopSimpleResponse> simple(
@PathVariable Long cakeShopId
) {
final CakeShopSimpleResponse response = shopService.searchSimpleById(cakeShopId);
return ApiResponse.success(response);
}
. . .
```
> ### etc

Feature: 케이크 샵 간단조회 API 구현

---

cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopDetailResponse.java
cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopSimpleResponse.java
cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
cakk-api/src/test/resources/sql/insert-cake-shop.sql
cakk-common/src/main/java/com/cakk/common/enums/LinkKind.java
cakk-domain/src/main/java/com/cakk/domain/converter/LinkKindConverter.java
cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopDetailParam.java
cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopSimpleParam.java
cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShopLink.java
cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShopOperation.java
cakk-domain/src/main/java/com/cakk/domain/repository/jpa/CakeShopLinkJpaRepository.java
cakk-domain/src/main/java/com/cakk/domain/repository/jpa/CakeShopOperationJpaRepository.java
cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeShopQueryRepository.java
cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopLinkReader.java
cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopOperationReader.java
cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopReader.java

#24
케이크 샵 상세조회 API를 구현하고 통합테스트를 작성했습니다. 통합 테스트를 진행하던 도중 쿼리에 오류를 발견하여 수정하였습니다. 쿼리는 다음과 같습니다.
(수정 사항이 몇개 있어서 pr이 커져버렸습니다..)
```sql
select cs1_0.shop_id,
cs1_0.shop_name,
cs1_0.thumbnail_url,
cs1_0.shop_bio,
cs1_0.shop_description,
cso1_0.operation_day,
csl1_0.link_kind,
csl1_0.link_path 
from cake_shop cs1_0 
join cake_shop_operation cso1_0 
on cs1_0.shop_id = cso1_0.shop_id 
join cake_shop_link csl1_0 
on cs1_0.shop_id = csl1_0.shop_id 
where cs1_0.shop_id = ?
```
```java
. . .
final ApiResponse response = objectMapper.convertValue(responseEntity.getBody(), ApiResponse.class);
final CakeShopDetailResponse data = objectMapper.convertValue(response.getData(), CakeShopDetailResponse.class);
assertEquals(HttpStatusCode.valueOf(200), …
```

Feature: 케이크 샵 상세조회 API 구현

---

cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeSearchByShopRequest.java
cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/service/cake/CakeServiceTest.java
cakk-api/src/test/resources/sql/insert-cake.sql
cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeQueryRepository.java
cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeReader.java

#40
이전에 구현했던 `카테고리 별 케이크 다건조회`와 비슷하여 비즈니스와 api 구현을 한번에 구현하여 PR 올렸습니다. Query는 다음과 같습니다.
```sql
select cs1_0.shop_id,
c1_0.cake_id,
c1_0.cake_image_url 
from cake c1_0 
join cake_shop cs1_0 
on c1_0.shop_id = cs1_0.shop_id 
join cake_category cc1_0 
on cc1_0.cake_id = c1_0.cake_id 
where cs1_0.shop_id = ? 
order by c1_0.cake_id desc 
limit ?
```
```java
. . .
public CakeImageListResponse findCakeImagesByCursorAndCakeShopId(final CakeSearchByShopRequest dto) {
final List<CakeImageResponseParam> cakeImages
= cakeReader.searchCakeImagesByCursorAndCakeShopId(dto.cakeId(), dto.cakeShopId(), dto.pageSize());
return CakeMapper.supplyCakeImageListResponse(cakeImages);
}
. . .
```
> ### etc

Feature: 케이크 샵에 속한 케이크 다건 조회 구현

---

cakk-api/src/main/java/com/cakk/api/annotation/OperationDays.java
cakk-api/src/main/java/com/cakk/api/annotation/validator/OperationValidator.java
cakk-api/src/main/java/com/cakk/api/controller/advice/GlobalControllerAdvice.java
cakk-api/src/main/java/com/cakk/api/dto/request/shop/CreateShopRequest.java
cakk-api/src/main/java/com/cakk/api/dto/request/shop/OperationDay.java
cakk-api/src/main/java/com/cakk/api/dto/request/shop/OperationDayRequest.java
cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
cakk-api/src/main/java/com/cakk/api/provider/jwt/JwtProvider.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/main/resources/application.yml
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
cakk-api/src/test/resources/application-test.yml
cakk-api/src/test/resources/sql/insert-cake-shop.sql
cakk-api/src/test/resources/sql/insert-test-user.sql
cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
cakk-domain/build.gradle
cakk-domain/src/main/java/com/cakk/domain/config/JacksonConfig.java
cakk-domain/src/main/java/com/cakk/domain/entity/audit/AuditEntity.java
cakk-domain/src/main/java/com/cakk/domain/entity/user/User.java

#42 
- [6b2f8ce](https://github.com/CAKK-DEV/cakk-server/pull/45/commits/6b2f8cec8821f55b54da06974347f4d641a70631) 영업 정보 POST시, 영업일자, 시간들에 대해 데이터 입력이 빠질 경우, RuntimeException이 발생하기 때문에 하나의 데이터로 통합했습니다
- 사용자 권한이 필요한 Post 요청 시, 통합 테스트 진행을 위해 SQL Script 순서 변경 및 데이터 추가가 있습니다
- 통합 테스트에서 발생한 오류를 보기 위해 Debug Level에서 log가 출력됩니다
- 토큰 관련해서 직렬화 및 역 직렬화 설정 추가했습니다
[93a0021](https://github.com/CAKK-DEV/cakk-server/pull/45/commits/93a0021c880e2a5679812ea27a8f15b7e6eb1ae5)
RequestBody에서 Validation Annotation에 의해 실패할 수 있는 최소 길이 설정이 꼭 필요함을 주의해야 합니다
```java
```
> ### etc

Test: Shop 도메인 유닛 테스트 및 통합 테스트 추가

---

cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopInfoResponse.java
cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
cakk-api/src/test/resources/sql/insert-cake-shop.sql
cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopInfoParam.java
cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopOperationParam.java
cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShop.java
cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeShopQueryRepository.java
cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopReader.java

#41
케이크 샵 상세 정보 조회 API를 개발했습니다. 특별한 로직 없이 조인하여 쿼리해왔습습니다.
```sql
select cs1_0.shop_id,
cs1_0.shop_address,
cs1_0.latitude,
cs1_0.longitude,
cso1_0.operation_day,
cso1_0.start_time,
cso1_0.end_time 
from
cake_shop cs1_0 
join
cake_shop_operation cso1_0 
on cs1_0.shop_id=cso1_0.shop_id 
where
cs1_0.shop_id=1
```
```java
```
> ### etc

Feature: 케이크 샵 상세 정보 조회 구현

---

.gitignore
cakk-api/build.gradle
cakk-api/src/main/java/com/cakk/api/config/CacheConfig.java
cakk-api/src/main/resources/application-local.yml
cakk-api/src/test/java/com/cakk/api/common/container/RedisTestContainer.java
cakk-api/src/test/resources/application-test.yml
cakk-domain/redis/build.gradle
cakk-domain/redis/src/main/java/com/cakk/domain/redis/annotation/RedisRepository.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/config/RedisConfig.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/RedisSetRepository.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/RedisValueRepository.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/impl/TokenRedisRepository.java
infra/redis/docker-compose.yaml
infra/redis/start.sh

#49
Redis 설정을 완료했습니다. 서브 모듈에 prod 환경 redis 설정 관련해서 업데이트 했으니 pull 받아서 활용하실 수 있고, 로컬에서 사용하시려면 따로 띄우셔야 합니다. 대부분의 경우 통합 테스트로 검증이 가능하기에 이를 활용해주세요.
repository 관련 추상화를 진행하고 싶었는데, 아직은 잘 된거 같진 않네요. 개발하면서 추가적으로 진행해봅시다
```java
public interface RedisSetRepository<T> {
void save(String value);
void increaseScore(String value, int delta);
List<T> findReverseByScoreRange(double min, double max);
}
```
> ### etc

Chore: Redis 설정 및 모듈 구현

---

cakk-api/build.gradle
cakk-api/src/main/java/com/cakk/api/annotation/OperationDays.java
cakk-api/src/main/java/com/cakk/api/dto/request/shop/CreateShopRequest.java
cakk-api/src/main/java/com/cakk/api/mapper/PointMapper.java
cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
cakk-api/src/main/java/com/cakk/api/service/slack/SlackService.java
cakk-api/src/main/java/com/cakk/api/validator/OperationDays.java
cakk-api/src/main/java/com/cakk/api/validator/OperationValidator.java
cakk-api/src/main/resources/application.yml
cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
cakk-api/src/test/java/com/cakk/api/common/base/ServiceTest.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
cakk-api/src/test/resources/sql/insert-cake-shop.sql
cakk-api/src/test/resources/sql/insert-cake.sql
cakk-domain/mysql/build.gradle
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/CakeShopInfoParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/CakeTag.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/BusinessInformation.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/event/EventMapper.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/event/shop/CertificationEvent.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
cakk-domain/mysql/src/test/java/com/cakk/domain/base/DomainTest.java
cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java

#48 
- CakeTag 연관 관계를 수정했습니다 https://github.com/CAKK-DEV/cakk-server/commit/291ae649c3f78ccc02b5d8548de3e30476960717  CakeTag가 Cake와 Tag 관계를 가지고 있어야 하는데 User와 관계를 가지고 있었습니다
- MySQL Version 명시 Dialect를 진행했습니다
- MySQL 8.0 버전 이후부터 사용할 수 있는 위치 기반 함수와 QueryDSL을 위해 의존성을 추가했습니다 WGS84(GPS) 기준의 위도 경도
- 경도(longitude), 위도(latitude) 를 기반으로 Point 객체로 추상화하여 구 형태의 객체 인스턴스로 활용할 수 있도록 리팩토링 했습니다
- SQL Script에서 Point 객체로 지정하여 Insert되도록 수정했습니다
MySQL에서 지원하는  `Spatial Index(공간 인덱스)` R-Tree 인덱스 알고리즘을 이용해 2차원의 데이터를 인덱싱하고 검색할 수 있습니다
내부 메커니즘은 B-Tree와 흡사합니다
이와 관련하여 Geometry(기하학적 도형) 정보를 관리할 수 있는 데이터 타입을 지원하고 있는데,
POINT, LINE, POLYGON 등 여러 TYPE중 가장 간단한 POINT(https://dev.mysql.com/doc/refman/8.0/en/gis-class-point.html) 를 선택했습니다
R-Tree 알고리즘에서는 MBR(Minimum Bounding Rectangle) 즉, 해당 …

Refactor: 위치 기반 케이크 샵 검색을 위한 리팩토링

---

cakk-api/src/main/java/com/cakk/api/annotation/RefreshToken.java
cakk-api/src/main/java/com/cakk/api/config/WebMvcConfig.java
cakk-api/src/main/java/com/cakk/api/controller/user/SignController.java
cakk-api/src/main/java/com/cakk/api/provider/jwt/JwtProvider.java
cakk-api/src/main/java/com/cakk/api/resolver/RefreshTokenResolver.java
cakk-api/src/main/java/com/cakk/api/service/user/UserService.java
cakk-api/src/main/resources/application.yml
cakk-api/src/test/java/com/cakk/api/common/container/RedisTestContainer.java
cakk-api/src/test/java/com/cakk/api/integration/user/SignIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/service/user/UserServiceTest.java
cakk-api/src/test/resources/application-test.yml
cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/config/RedisConfig.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/impl/TokenRedisRepository.java

#44
Refresh Token을 활용한 토큰 재발급 기능을 구현하였습니다. 다만, access token 과 refresh token의 차이가 없는 것 같아 이 부분에 대한 수정을 추후에 할 예정입니다. 
```java
@Transactional(readOnly = true)
public JwtResponse recreateToken(final String refreshToken) {
final boolean isBlackList = tokenRedisRepository.isBlackListToken(refreshToken);
if (isBlackList) {
throw new CakkException(ReturnCode.BLACK_LIST_TOKEN);
}
final User user = jwtProvider.getUser(refreshToken);
final long expiredSecond = jwtProvider.getRefreshTokenExpiredSecond();
tokenRedisRepository.registerBlackList(refreshToken, expiredSecond);
return JwtResponse.from(jwtProvider.generateToken(user));
}
```
> ### etc

Feature: 토큰 재발급 로직 작성

---

cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
cakk-api/src/main/java/com/cakk/api/controller/user/MyPageController.java
cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeSearchByLocationRequest.java
cakk-api/src/main/java/com/cakk/api/dto/request/like/LikeCakeSearchRequest.java
cakk-api/src/main/java/com/cakk/api/dto/response/cake/CakeImageListResponse.java
cakk-api/src/main/java/com/cakk/api/dto/response/like/LikeCakeImageListResponse.java
cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
cakk-api/src/main/java/com/cakk/api/service/like/LikeService.java
cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
cakk-api/src/test/java/com/cakk/api/common/base/ServiceTest.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/integration/user/LikeIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/integration/user/MyPageIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/service/like/LikeServiceTest.java
cakk-api/src/test/resources/sql/insert-like.sql
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/like/LikeCakeImageResponseParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeLikeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeLikeReader.java

#71
좋아요 한 케이크 목록 조회를 구현했습니다. 해당 구현 시 가장 신경 쓴 부분은 `도메인을 분리할 것인가?`와 `API 설계를 어떻게 할 것인가?` 였습니다. 좋아요와 관련된 기능은 다음과 같습니다.
- 좋아요 한 케이크 조회
- 좋아요 한 케이크 샵 조회
- 케이크 좋아요 or 취소
- 케이크 샵 좋아요 or 취소
조회의 경우, 기존 조회와 다르게 cake_like_id를 기준으로 페이지네이션이 이루어지고, 좋아요 혹은 좋아요 취소 기능은 새로운 행동으로 판단하여 비즈니스를 분리했습니다. 또, 조회 APi의 경우, cake 혹은 cake_shop에서 제공하는 데이터이지만, 특정 유저에 대한 데이터임을 고려하여 ~/me/liked-cake 혹은 ~/me/liked-shop 으로 설계했습니다.
추가로 기존에 getAuthToken() 이라는 공통 메서드를 IntegrationTest에 추가했었는데, Authorization 헤더를 위해 가져오는 경우가 대부분이라고 판단하여 getAuthHeader()이라는 공통 메서드를 추가하였고, 해당 메서드를 모든 통합 테스트에 적용하였습니다.
```sql
select cs1_0.shop_id,
c1_0.cake_id,
cl1_0.cake_like_id,
c1_0.cake_image_url 
from cake_like cl1_0 
join cake c1_0 
on cl1_0.cake_id=c1_0.cake_id 
join cake_shop cs1_0 
on …
```

Feature: 좋아요 한 케이크 목록 조회 구현

---

cakk-api/src/main/java/com/cakk/api/service/like/LikeService.java
cakk-api/src/test/java/com/cakk/api/service/like/LikeServiceTest.java
cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeLikeJpaRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeLikeReader.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeLikeWriter.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/LockRedisRepository.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/RedisValueTemplate.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/impl/RedisStringValueTemplate.java

#74
`케이크 좋아요`를 구현하였습니다. 현실적으로 동시성 문제가 발생하진 않을 것 같지만, 서버 개발자의 덕목은 `상상 버그`라고 생각하여 동시성 처리를 추가했습니다. Lettuce를 활용하여 동시성을 해결했습니다. 동시성과 관련된 테스트는 다음 PR에서 통합테스트와 함께 진행할 예정입니다. 
```java
@Transactional
public void likeCake(final User user, final Long cakeId) {
final Cake cake = cakeReader.findById(cakeId);
final CakeLike cakeLike = cakeLikeReader.findOrNullByUserAndCake(user, cake);
lockRedisRepository.executeWithLock(RedisKey.LOCK_CAKE_LIKE, 1000L,
() -> likeCakeOrCancel(cakeLike, user, cake)
);
}
```
> ### etc

Feature: 케이크 좋아요 기능 구현

---

cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/dto/request/link/UpdateLinkRequest.java
cakk-api/src/main/java/com/cakk/api/mapper/LinkMapper.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-domain/mysql/build.gradle
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/link/UpdateLinkParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShopLink.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java

#87
- JPA가 지향하는 Entity에서 도메인 로직을 담고, Cascade, Orphan Option을 활용 -> 영속성 컨텍스트를 활용하여 데이터의 정합성이 올바르게 유지될 수 있도록 코드를 작성했습니다.
```java
public void updateShopLinks(List<CakeShopLink> cakeShopLinks) {
this.cakeShopLinks.clear(); // 영속성 컨텍스트에 올라온 기존 외부 링크 제거
cakeShopLinks.forEach(cakeShopLink -> { // 새롭게 요청 받은 외부 링크 삽입 위한 로직
cakeShopLink.updateCakeShop(this);
this.cakeShopLinks.add(cakeShopLink);
});
}
```
> ### etc
* 기존 외부 링크들이 존재하면, 해당 외부 링크가 INSTAGRAM, KAKAO, WEB인지 검사하는 로직을 통해 도메인 로직을 구상하려고 했는데 
* 클라이언트 요청의 아무래도 PUT이다 보니 , 외부 링크에 대한 데이터 정합성을 서버에서 정확히 관리하기 위해 기존 링크 삭제 후, 새롭게 삽입하는 로직으로 작성했습니다.

Feature: 케이크 샵 외부 링크 수정 기능 추가

---

cakk-api/src/main/java/com/cakk/api/controller/user/MyPageController.java
cakk-api/src/main/java/com/cakk/api/dto/request/like/HeartCakeShopSearchRequest.java
cakk-api/src/main/java/com/cakk/api/dto/response/like/HeartCakeShopListResponse.java
cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
cakk-api/src/test/java/com/cakk/api/integration/user/HeartIntegrationTest.java
cakk-api/src/test/resources/sql/insert-cake.sql
cakk-api/src/test/resources/sql/insert-heart.sql
cakk-common/src/main/java/com/cakk/common/utils/SetUtils.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/like/HeartCakeShopResponseParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopHeartQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeHeartReader.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopHeartReader.java

#79
저번에 말씀해주신 것처럼 pageSize만큼 가져오지 못하는 경우가 있습니다. 이를 해결하기 위해 아래와 같이 id를 먼저 조회했습니다.
```java
select
csh1_0.shop_heart_id 
from
cake_shop_heart csh1_0 
where
csh1_0.user_id=:userId
limit :pageSize
```
이후 id 리스트를 활용하여 케이크 샵을 조회했습니다.
```java
select
csh1_0.shop_heart_id,
cs1_0.shop_id,
cs1_0.thumbnail_url,
cs1_0.shop_name,
cs1_0.shop_bio,
c1_0.cake_image_url,
cso1_0.operation_day 
from
cake_shop_heart csh1_0 
join
cake_shop cs1_0 
on csh1_0.shop_id=cs1_0.shop_id 
join
users u1_0 
on csh1_0.user_id=u1_0.user_id 
join
cake_shop_operation cso1_0 
on cs1_0.shop_id=cso1_0.shop_id 
join
cake c1_0 
on cs1_0.shop_id=c1_0.shop_id 
where
csh1_0.shop_heart_id in :cakeShopIds 
order by
csh1_0.shop_heart_id desc
```
기존에 구현해주신 CakeShops 컬렉션은 멤버변수가 달라 활용하지 못했습니다.
> ### Core …

Feature: 케이크 샵 좋아요 목록 조회 구현

---

cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeCreateRequest.java
cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeUpdateRequest.java
cakk-api/src/main/java/com/cakk/api/dto/request/operation/UpdateShopOperationRequest.java
cakk-api/src/main/java/com/cakk/api/dto/request/shop/UpdateShopAddressRequest.java
cakk-api/src/main/java/com/cakk/api/dto/response/cake/CakeDetailResponse.java
cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/resources/sql/insert-cake.sql
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/cake/CakeCreateParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/cake/CakeDetailParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/tag/TagParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeReader.java

#88 
- 상세 조회 API는 다른 API를 사용하고 있지만 필요성에 의해 만들었습니다.
도메인 모델 패턴을 활요한 객체 간의 책임 부여
```java
public CakeDetailResponse findCakeDetailById(Long cakeId) {
final CakeDetailParam cake = cakeReader.searchCakeDetailById(cakeId);
return CakeMapper.cakeDetailResponseFromParam(cake);
}
@Transactional
public void createCake(CakeCreateParam param) {
CakeShop cakeShop = cakeShopReader.findByIdAndOwner(param.cakeShopId(), param.owner());
Cake cake = param.cake();
List<Tag> tags = param.tagNames()
.stream()
.map(tagName -> tagReader.findByTagName(tagName).orElseGet(() -> tagWriter.saveTag(tagName)))
.toList();
cake.registerTags(tags);
cake.registerCategories(param.cakeCategories());
cakeShop.registerCake(cake);
}
```
> ### etc

Feature: 케이크 상세 조회, 생성 기능 추가

---

cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/listener/shop/CertificationEventListener.java
cakk-api/src/main/java/com/cakk/api/listener/views/ViewsIncreaseEventListener.java
cakk-api/src/main/java/com/cakk/api/service/views/ViewsService.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/event/EventMapper.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/event/views/CakeIncreaseViewsEvent.java

#103
케이크 조회수 증가 이벤트 리스닝 로직을 구현하였습니다. 케이크 리스트에서 케이크를 클릭 시 케이크 샵 간단 조회 API를 호출 하는데, 이 때 Querystring으로 cakeId를 담아서 요청한다면 해당 케이크에 대하여 조회수를 증가시킵니다.
만약 잘못된 cakeId여도 오류가 나지 않도록 처리했습니다.
```java
@Transactional(readOnly = true)
public void increaseCakeViews(final Long cakeId) {
if (isNull(cakeId)) {
return;
}
try {
final Cake cake = cakeReader.findById(cakeId);
final CakeIncreaseViewsEvent event = cake.getInCreaseViewsEvent();
publisher.publishEvent(event);
} catch (CakkException ignored) {
// ignored
}
}
```
> ### etc

Feature: 케이크 조회수 증가 이벤트 리스닝 구현

---

cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeSearchByLocationRequest.java
cakk-api/src/main/java/com/cakk/api/dto/request/shop/CakeShopSearchRequest.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java

#102 
- OneToOne은 Lazy Loading이 안되기에 fetch join으로 수정
- 검색 API에서 위치 정보 Optional로 변경 및 쿼리 순서 변경
```java
```
> ### etc

Fix: 검색 시 위치 기반 미동의 시 조건부 로직으로 수정

---

cakk-api/src/main/java/com/cakk/api/controller/user/SignController.java
cakk-api/src/main/java/com/cakk/api/dto/event/EmailWithVerificationCodeSendEvent.java
cakk-api/src/main/java/com/cakk/api/dto/request/user/GenerateCodeRequest.java
cakk-api/src/main/java/com/cakk/api/dto/request/user/VerifyEmailRequest.java
cakk-api/src/main/java/com/cakk/api/listener/user/EmailSendEventListener.java
cakk-api/src/main/java/com/cakk/api/mapper/EventMapper.java
cakk-api/src/main/java/com/cakk/api/service/user/EmailVerificationService.java
cakk-api/src/main/resources/application-local.yml
cakk-api/src/test/resources/application-test.yml
cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
cakk-common/src/main/java/com/cakk/common/utils/RandomUtils.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/EmailVerificationRedisRepository.java
cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/TokenRedisRepository.java
cakk-external/build.gradle
cakk-external/src/main/java/com/cakk/external/config/MailConfig.java
cakk-external/src/main/java/com/cakk/external/service/MailService.java

#124
메일 전송 관련 기능을 구현하였습니다. 로컬에서 테스트가 안돼서 ec2 환경에서는 잘될지 테스트 해보려합니다. 코드와 로직만 보시면 될 것 같습니다.
```java
public void sendEmailForVerification(final GenerateCodeRequest dto) {
final String email = dto.email();
final String code = RandomUtils.generateRandomStringOnlyNumber(6);
emailVerificationRedisRepository.save(email, code);
final EmailWithVerificationCodeSendEvent emailEvent = EventMapper.supplyEmailWithVerificationCodeSendEventBy(email, code);
applicationEventPublisher.publishEvent(emailEvent);
}
public void checkEmailVerificationCode(final VerifyEmailRequest dto) {
final String email = dto.email();
final String code = dto.code();
final String verificationCode = emailVerificationRedisRepository.findCodeByEmail(email);
if …
```

Feature: 이메일 인증 기능 구현

---

cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
cakk-api/src/main/java/com/cakk/api/dto/request/shop/CakeShopSearchByViewsRequest.java
cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
cakk-api/src/test/resources/application-test.yml
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/CakeShops.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/CakeShopParam.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java

#133
인기 케이크 샵 조회를 구현했습니다. 이전에 만드신 일급 컬렉션을 활용하였고, test 속도를 향상시키기 위해 h6spy 를 비활성화 하였습니다.
```java
@Transactional(readOnly = true)
public CakeShopSearchResponse searchCakeShopsByCursorAndViews(CakeShopSearchByViewsRequest dto) {
final long offset = isNull(dto.offset()) ? 0 : dto.offset();
final int pageSize = dto.pageSize();
final List<Long> cakeShopIds = cakeShopViewsRedisRepository.findTopShopIdsByOffsetAndCount(offset, pageSize);
if (isNull(cakeShopIds) || cakeShopIds.isEmpty()) {
return ShopMapper.supplyCakeShopSearchResponseBy(List.of());
}
final List<CakeShop> result = cakeShopReader.searchShopsByShopIds(cakeShopIds);
final List<CakeShopBySearchParam> cakeShopBySearchParams = ShopMapper.supplyCakeShopBySearchParamListBy(result);
final …
```

Feature: 인기 케이크 샵 조회 구현

---

build.gradle
lombok.config

#155
일단 기본적인 jacoco 설정하여 커버리지를 체크할 수 있는 환경을 구성하였습니다. 현재 목표로 잡고 있는 70에 도달하면 80으로 올리거나 codecov 설정에 대해 고려하겠습니다. 다만, 70이라고 해서 70에 딱 맞추기 보다는 같이 최대한 많은 TC를 생산해내는게 목표입니다.
> ### Coverage 미달성 로그
```log
> Rule violated for class com.cakk.api.Application: lines covered ratio is 0.50, but expected minimum is 0.70
Rule violated for class com.cakk.api.listener.user.EmailSendEventListener: lines covered ratio is 0.00, but expected minimum is 0.70
Rule violated for class com.cakk.api.provider.oauth.impl.KakaoAuthProvider: lines covered ratio is 0.00, but expected minimum is 0.70
Rule violated for class com.cakk.api.provider.oauth.impl.GoogleAuthProvider: lines covered ratio is 0.00, but expected minimum is 0.70
Rule violated for class …
```

Chore: jacoco 설정

---

cakk-external/src/main/java/com/cakk/external/config/MailConfig.java
cakk-external/src/main/java/com/cakk/external/service/MailService.java

CAKK-7
- 잘못된 로직 수정
```java
@Bean
public JavaMailSender javaMailSender() {
JavaMailSenderImpl mailSender = new JavaMailSenderImpl();
mailSender.setHost(host);
mailSender.setPort(port);
mailSender.setUsername(username);
mailSender.setPassword(password);
mailSender.setDefaultEncoding("UTF-8");
mailSender.setJavaMailProperties(getMailProperties());
return mailSender;
}
```
어이없게도 잘 설정한 mailSender가 아닌 `new JavaMailSenderImpl()`로 다시 보내고 있더군요,,,
> ### etc

Fix: 이메일 전송 로직 수정

---

cakk-api/src/main/resources/application.yml
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java

- 필요하지 않은 join 제거
- in 쿼리를 발생시키기 위한 batch size 설정 추가
```sql
// 3개의 쿼리로 최적화 - 페이지네이션을 위한 limit 발생
select
cs1_0.shop_id,
bi1_0.shop_id,
bi1_0.business_number,
bi1_0.created_at,
bi1_0.updated_at,
bi1_0.user_id,
cs1_0.created_at,
cs1_0.deleted_at,
cs1_0.heart_count,
cs1_0.like_count,
cs1_0.linked_flag,
cs1_0.location,
cs1_0.shop_address,
cs1_0.shop_bio,
cs1_0.shop_description,
cs1_0.shop_name,
cs1_0.thumbnail_url,
cs1_0.updated_at 
from
cake_shop cs1_0 
left join
business_information bi1_0 
on cs1_0.shop_id=bi1_0.shop_id 
where
lower(cs1_0.shop_bio) like '%3%' escape '!' 
or lower(cs1_0.shop_description) like '%3%' escape '!' 
order by
cs1_0.shop_id desc 
limit
10
select
c1_0.shop_id,
c1_0.cake_id,
c1_0.cake_image_url,
c1_0.created_at,
c1_0.deleted_at, …
```

Fix: 케이크 샵 검색 시, 페이지네이션이 이루어지지 않은 부분 수정 및 JPA 최적화

---

cakk-api/src/main/java/com/cakk/api/dto/request/user/CertificationRequest.java
cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
cakk-api/src/test/resources/sql/insert-business-information.sql
cakk-api/src/test/resources/sql/insert-cake-shop.sql
cakk-api/src/test/resources/sql/insert-cake.sql
cakk-api/src/test/resources/sql/insert-heart-for-concurrency-test.sql
cakk-api/src/test/resources/sql/insert-like-for-concurrency-test.sql
cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
cakk-common/src/main/java/com/cakk/common/enums/Role.java
cakk-common/src/main/java/com/cakk/common/enums/VerificationStatus.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/user/DefaultVerificationPolicy.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/user/VerificationPolicy.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/BusinessInformation.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/User.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/EventMapper.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/BusinessInformationJpaRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
cakk-domain/mysql/src/test/java/com/cakk/domain/base/DomainTest.java
cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java
cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/VerificationPolicyTest.java

**주요 변경 사항**
- 사장님 인증 요청 시, cakeShopId nullable 제거
- CakeShop linked_flag 제거
- 테스트 코드 리팩토링
- User Role - Business Owner 제거
- 사장님 인증 요청 시, 검증과 업데이트 로직 분리 (VerificationPolicy)
- 케이크 샵 또는 케이크 정보 수정 시, 인증(Approved) 여부와 User 정보 여부로 조건부 쿼리 업데이트
**테스트 코드 주요 사항**
요청 단계에 따른 테스트 코드로 검증
user role이 admin이 아닐 떄, 케이크 또는 케이크 샵 업데이트 시 조건부 쿼리 동작 여부 검증
cake_shop에서 linked_flag column이 제거됨으로써 sql 파일 수정
```java
```
> ### etc

Refactor: 케이크 샵 인증 요청 로직 개선

---

cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
cakk-api/src/test/java/com/cakk/api/service/like/HeartServiceTest.java
cakk-api/src/test/resources/sql/insert-cake.sql
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/User.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/CakeHeartMapper.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeHeartReader.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeReader.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeHeartWriter.java

CAKK-54
케이크 하트 기능이 트랜잭션 스크립트 패턴으로 작성돼있다고 생각들어 객체지향적으로 리팩토링(도메인 모델 패턴) 해보았습니다. 리뷰 후에 케이크 샵 하트 및 기대돼요 기능까지 비슷하게 적용하겠습니다. 
```java
@DistributedLock(key = "#cakeId")
public void heartCake(final User user, final Long cakeId) {
final Cake cake = cakeReader.findById(cakeId);
if (!cake.isHeartedBy(user)) {
user.heartCake(cake);
} else {
user.unHeartCake(cake);
}
}
```
> ### etc

Refactor | CAKK-54 |  케이크 하트 기능 리팩토링

---

cakk-api/build.gradle.kts
cakk-api/src/main/java/com/cakk/api/config/MessageTemplateConfig.java
cakk-external/src/main/java/com/cakk/external/extractor/VerificationCodeMimeMessageExtractor.kt
cakk-external/src/main/java/com/cakk/external/sender/EmailMessageSender.kt
cakk-external/src/main/java/com/cakk/external/sender/SlackMessageSender.kt

CAKK-61
지난 PR에서 추상화 및 템플릿 콜백 패턴을 적용했으나 API 모듈에서 일부 Extractor와 Sender에 대해서 하위 모듈인 external 모듈에 의존하는, DIP 위반 사례가 있었습니다. 여러 방법을 고민한 끝에 API 모듈에 의존성을 추가 시키고, Extractor와 Sender 의존성 주입에 대한 책임을 API 모듈에 두면서 DIP 문제를 해결했습니다.
```java
@Configuration
public class MessageTemplateConfig {
private final JavaMailSender javaMailSender;
private final SlackApi slackApi;
private final String senderEmail;
private final Boolean isEnable;
public MessageTemplateConfig(
JavaMailSender javaMailSender,
SlackApi slackApi,
@Value("${spring.mail.username}")
String senderEmail,
@Value("${slack.webhook.is-enable}")
Boolean isEnable
) {
this.javaMailSender = javaMailSender;
this.senderEmail = senderEmail;
this.isEnable = isEnable;
this.slackApi = slackApi;
}
@Bean
public …
```

Refactor | CAKK-61 | DIP 위반 문제 해결

---

cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/annotation/DomainFacade.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/facade/cake/CakeManagerFacade.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/TagJpaRepository.java
cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/TagReader.java

- 파샤드 패턴으로 로직 리팩토링을 수행했습니다
```java
```
> ### etc

Refactor | CAKK-57 | 케이크 도메인 로직 리팩토링

---

build.gradle.kts
cakk-admin/build.gradle.kts
cakk-api/build.gradle.kts
cakk-api/src/test/java/com/cakk/api/provider/AppleAuthProviderTest.kt
cakk-api/src/test/java/com/cakk/api/provider/KakaoAuthProviderTest.kt
cakk-batch/build.gradle
cakk-core/build.gradle.kts
cakk-domain/mysql/build.gradle.kts
cakk-domain/redis/build.gradle.kts
cakk-external/build.gradle.kts
gradle.properties
libs.versions.toml
settings.gradle.kts

CAKK-95
버전 관리를 편하게 하기 위해 의존성 관리 방식을 리팩토링 했습니다.
- DependencyResolutionManagement 활성화
- 의존성 관리방식을 Gradle Version Catalog로 변경
생략
> ### etc

Refactor | CAKK-95 | 의존성 관리 방식 관련 리팩토링
